### ISSUE TITLE
wrong github link in the footer

### ISSUE THREAD

**Issue by trebmuh** [surge-synthesizer/surge-synthesizer.github.io#103]
https://github.com/surge-synthesizer/surge-synthesizer.github.io/blob/ff81c3798d3d2f0b76eea8f01855affcf05e37cf/_includes/footer.html#L9

The "Star" button in the footer is giving me a https://github.com// link (yes, with two slashes).

**Comment by baconpaul** [comment]
Oh we need to set that site variable I guess in the tank right?

**Comment by trebmuh** [comment]
Probably that "https://github.com/surge-synthesizer/surge" would do I guess.

**Comment by baconpaul** [comment]
Oh yeah that would work of course! I’ll fix it or set the variable when I’m next at my computer. Thanks for the careful eyes

**Comment by baconpaul** [comment]
Oh and my comment originally got autocorrected. “Tank” should be “ - otherwise it makes very little sense :)

**Comment by baconpaul** [comment]
iPhones are not for github
Yaml
Just trust me I’m not typing nonsense. Just posting it. Chuckle

**Comment by trebmuh** [comment]
:smile:

**Comment by baconpaul** [comment]
Yeah the fix was to add it to _config.yml but great catch still! Pushing new _config now

**Comment by trebmuh** [comment]
Nice :+1:
