### ISSUE TITLE
LV2: Patch changes randomly when reooening the GUI or reloading the session

### ISSUE THREAD

**Issue by unfa** [surge-synthesizer/surge-synthesizer.github.io#104]
Today I've tried the LV2 build in Linux and I've had my patch change randomly during work.

The oscillators seemed to be reverted back to Sawtooth when I closed and opened again the UI.

I ended up replacing Surge with something else, to finish the project.

Anybody had similar issues? I'm running Manjaro, used Surge LV2 in Ardour 5.12.
I've installed Surge LV2 from AUR.

**Comment by baconpaul** [comment]
Yeah the lv2 is broken in this regard and the team of @jocima and crystalmath on the irc are working on fixing it. They will fix it before the 162 release (I hope!)

**Comment by baconpaul** [comment]
Linking to https://github.com/surge-synthesizer/surge/issues/1139 and closing this one.
