### ISSUE TITLE
Binary Linux VST Release

### ISSUE THREAD

**Issue by drewofdoom** [surge-synthesizer/surge-synthesizer.github.io#112]
I would love to test/use this and contribute with bug reports, but I am not running a Debian-based distribution. Would it be possible to release a version of the binary Linux VST, so that it can be run without requiring .deb installation?

**Comment by tank-trax** [comment]
you can extract the deb file using Ark

it's in the file called `data.tar.xz`

**Comment by baconpaul** [comment]
Hi! We had a conversation about this https://github.com/surge-synthesizer/surge/issues/1143 over on that issue. Do you mind if we close this one as a duplicate and you can hop over there?

The process that makes the deb is just a shell script. We could modify it to also make a .tar.gz of the deb file contents easily along with a README and push that to the upload I guess. I think I detailed that over in the other issue. But as @tank-trax said I think most people just unpack the deb file if they don't have deb based systems.
