### ISSUE TITLE
Surge doesn't remember delay FX tempo sync

### ISSUE THREAD

**Issue by d3p4z** [surge-synthesizer/surge-synthesizer.github.io#123]
Hi,

I've tried Surge today and I've created a patch that uses a delay FX with tempo sync. Every time I reload the patch, tempo sync is disabled and I have to enable it manually. Also happens after loading in my DAW (Reaper) any project with any Surge instance that had tempo sync enabled.

Steps to reproduce the bug:
- Add delay FX to any patch (choose any delay preset, seems that all of them use tempo sync)
- In the delay FX options, right click the slider labeled as "right" and check that "Temposync" is enabled in the context menu.
- Repeat the same for the slider labeled as "left".
- Save the patch using the store button.
- Reload the patch using the patch browser | Or save/reload the project using the DAW.
- "Temposync" is disabled for both left and right channels (and the delay doesn't sound synced anymore)

System where the bug was experienced:
OS: Windows 10 x64
Surge version: 1.6.4.1 (VST x64)
DAW: Reaper 5.984 x64

Feel free to ask me any additional information.
Keep up the good work, It's a great synth with an amazing sound and tons of versatility.

Thank you in advance.

**Comment by baconpaul** [comment]
Oooh thanks that is definitely not the expected behavior. 

Can you make a zip of the patch you stored and attach it here? I will also try in my environment and see if I see the same.

**Comment by baconpaul** [comment]
Oh also and a minor administrative detail, I moved this issue over to the code repo so it is now https://github.com/surge-synthesizer/surge/issues/1401 And I’ll close this copy of it. Hope that’s OK!

**Comment by baconpaul** [comment]
Just a note that this is fixed and if you download a nightly from surge-synthesizer it should all work

Your reaper may have streamed temposync off once but if you reset it and save should be all good

This fix will ship in 1.6.5 in January 2020
