### ISSUE TITLE
AVAST is reporting a virus in Surge-1.6.5-Setup.exe

### ISSUE THREAD

**Issue by blatanville** [surge-synthesizer/surge-synthesizer.github.io#128]
![2020-02-08_12-43-47](https://user-images.githubusercontent.com/1321925/74089603-ec54e280-4a70-11ea-83f5-4b87d0763526.png)

**Comment by baconpaul** [comment]
We are not sure what is causing this warning but our pipeline build was on a fresh azure vm and so we assume it is a false positive. 

If you think it is not could you provide more information in a fresh issue in the surge/ repo?

Thanks!
