### ISSUE TITLE
Surge FXP presets are not showing up in Bitwig

### ISSUE THREAD

**Issue by carlca** [surge-synthesizer/surge-synthesizer.github.io#131]
- macOS 10.14.6
- Bitwig 3.1.2
- Surge 1.6.6

Despite having standard FXP format presets, the Surge presets are not showing up in Bitwig's file browser despite my having added `/Library/Application Support/Surge` (where the FXPs are located), to Bitwig's Locations in Settings.

Any ideas why?

**Comment by carlca** [comment]
Don't worry. I've found them - I haven't been up long 😉

**Comment by baconpaul** [comment]
Hey great. You reopened the issue though? Can we close it again?

**Comment by carlca** [comment]
One significant point is that, on the Mac at least, I had to install the VST rather than the VST3, for the presets to load Surge correctly.

**Comment by baconpaul** [comment]
Oh yeah there's a VST3 preset API we don't support yet.

That's all over in this issue https://github.com/surge-synthesizer/surge/issues/1256
