### ISSUE TITLE
Installation issue... forgot "browse" button

### ISSUE THREAD

**Issue by vpxm** [surge-synthesizer/surge-synthesizer.github.io#147]
Just installed this software, 'cause I'm curious.
I have tons of stuff in my Program Files folder, from Auddict, to XLN Audio... that's just VST lol
So where exactly does this thing install itself???

**Comment by baconpaul** [comment]
VST3 installs itself in c:\program files\Common Files\VST3\
Surge has a great manual! Here's the complete information: https://surge-synthesizer.github.io/manual/#windows
Best

**Comment by vpxm** [comment]
Thank you Paul!!
