### ISSUE TITLE
Top Menu Bar changes position depending on page, and does not highlight/signify selected page

### ISSUE THREAD

**Issue by esaruoho** [surge-synthesizer/surge-synthesizer.github.io#15]
![top menu discrepancies](https://user-images.githubusercontent.com/4966687/51799213-99bed480-2227-11e9-8f79-1c63a1525945.gif)

**Comment by itsmedavep** [comment]
Uffda. Somehow I made this worse. Now its like this. 

<img width="411" alt="screen shot 2019-02-04 at 9 31 08 pm" src="https://user-images.githubusercontent.com/11078351/52251721-39353480-28c4-11e9-8fef-90619d1476c4.png">

Ill come back to this one later. Those links are generated in code. I must have adjusted the style on an element. Ill see if I can get this one and the highlight thing tomorrow.

**Comment by kzantow** [comment]
if we merge a nicer rewritten version of the about page into the small about section on the main page, we could get rid of the menu altogether and kill 2 birds ;)

**Comment by itsmedavep** [comment]
Not really though. I messed up the style somehow so if we end up with any additional pages we will have the same problem. I gotta figure out so we can add more pages in the future.

**Comment by mkruselj** [comment]
Fixed by the great hamburger menu implementation.
