### ISSUE TITLE
Audio Input Wiki Host info is out of date

### ISSUE THREAD

**Issue by djaychela** [surge-synthesizer/surge-synthesizer.github.io#173]
Hi - I hope this is the right way to report this.

The Audio Input page of the Wiki[1] has a couple of entries that are now out-of-date.

In the known compatible audio software section, it currently says the only version of Cubase that will work for this is Cubase Pro, and that Elements doesn't work.

Since version 11, Cubase Pro, Artist and Elements all support sidechain input, and work fine with Surge's Audio Input mode.
Cubase Pro has indeed offered sidechain since V4.1, so I'm not sure how to mark this differentiation cleanly, but I'd suggest something like this:

Cubase Pro (Version > 4.1), Cubase Artist, Elements (Version > 11)

Also, in the last section - the list of known issues, the following is present:

**CUBASE ESSENTIALS AND ELEMENTS: No support for sidechains**

I think now the versions this would apply to are Cubase AI and Cubase LE (both of which I'm unable to test, but I'm fairly sure neither support sidechain).

Sorry if this isn't the right arena to report this.

[1]- https://github.com/surge-synthesizer/surge-synthesizer.github.io/wiki/Using-Surge-as-an-effect-(and-vocoder)

**Comment by mkruselj** [comment]
Thanks for the report, we will update the wiki!

**Comment by mkruselj** [comment]
Wiki updated, so closing the issue!
