### ISSUE TITLE
Maybe a skin issue, not sure, but grey box is slightly offset to the left within the black border of FX

### ISSUE THREAD

**Issue by esaruoho** [surge-synthesizer/surge-synthesizer.github.io#18]
<img width="640" alt="surge" src="https://user-images.githubusercontent.com/4966687/51799267-0fc33b80-2228-11e9-8e17-93f0a1452a9c.png">

**Comment by itsmedavep** [comment]
Interesting. Ill take a look. It would be in the skin BUT there are a couple of considerations. 

I zoomed the heck out of the GUI to make the screenshots. I did see some artifacts as various zoom levels. So, I will check if this is in the skin file or not. If it is I will fix.

**Comment by itsmedavep** [comment]
The skin file looks like this:

<img width="735" alt="screen shot 2019-01-27 at 7 47 39 am" src="https://user-images.githubusercontent.com/11078351/51801791-de3a7800-2207-11e9-879b-cb5020c6a629.png">

So we are drawing the color inside those boxes in code. My skin does not do that. 

My skin file matches exactly the original graphic WRT stroke width and placement. Im inclined to believe this is a visual artifact from zooming the UI. I have seen a couple of other places that exhibit this. Ill open an issue in the main project for those when I have time.

Original Bitmap from 1.5 Surge:
<img width="495" alt="screen shot 2019-01-27 at 7 51 21 am" src="https://user-images.githubusercontent.com/11078351/51801823-6c166300-2208-11e9-8447-ca7e2b3d8b90.png">

My Skin:
<img width="690" alt="screen shot 2019-01-27 at 7 51 32 am" src="https://user-images.githubusercontent.com/11078351/51801824-733d7100-2208-11e9-8a4f-0744691dba9b.png">

Closing this issue but will raise on on zoom artifacts in the synth project.

**Comment by baconpaul** [comment]
Yeah raise this in the synth please and one of us can look st that drawing code one dat
