### ISSUE TITLE
dropdown for manual(s)

### ISSUE THREAD

**Issue by mynameismuhl** [surge-synthesizer/surge-synthesizer.github.io#184]
since i don't know how to jeckyll (have not looked into it yet)
i drop idea here for now:

- make drop-down menu for manual(s) in page header
- call it "Manual"  and the sub categories English, Deutsch, Français etc. (sorted alphabetical(?))
- (no national flags ... please) 

 so it takes same space in header menu for the hundreds of translations that may soon come in...

**Comment by mkruselj** [comment]
Flags would be cool actually. And the menu entry should be called Documentation. But yeah I don't know Jekyll either 🙁

**Comment by mkruselj** [comment]
Implemented now!
