### ISSUE TITLE
footer's three items are not 100% aligned (text, twitter-icon, github star)

### ISSUE THREAD

**Issue by esaruoho** [surge-synthesizer/surge-synthesizer.github.io#22]
<img width="1202" alt="surge" src="https://user-images.githubusercontent.com/4966687/51803749-2f2a8a80-2261-11e9-9bb6-9565095642d4.png">

**Comment by itsmedavep** [comment]
Odd. I can't make this happen. Is there any more context you can provide about what was going on when you saw this? Or recheck. I did fix some stuff in the footer recently.

![footer](https://user-images.githubusercontent.com/11078351/51808212-9262ef80-2256-11e9-9309-ebd915502926.gif)

**Comment by itsmedavep** [comment]
@esaruoho 

Do you still see this issue? Can this be closed now?

**Comment by esaruoho** [comment]
@itsmedavep well it could be tweaked a bit further - now the tweet + star are not in alignment with the text on chrome, at least :)

![surge](https://user-images.githubusercontent.com/4966687/52198949-3bb86f80-286d-11e9-89ec-0a7f8cc48348.jpg)

**Comment by esaruoho** [comment]
but i guess it could be closed if we're overall happy with this

**Comment by esaruoho** [comment]
safari:
<img width="901" alt="surge" src="https://user-images.githubusercontent.com/4966687/52234714-f7f45300-28ca-11e9-862a-2276f9f4c79c.png">

**Comment by itsmedavep** [comment]
Alright @esaruoho Im going in on these things again!

Wish me luck.

**Comment by itsmedavep** [comment]
@esaruoho 

Alright. You may not like this fix but this is how I have fixed this now. At the least it doesn't  get wonky on Safari any longer. 

Im not trying to make the text and buttons align perfectly anymore. The button are stacked. Ive spent waaaaayyyyy to much time looking at this. 

Cross browser compatibility PFFTTTT 

Here is what this is changed to now.

Chrome:
<img width="1440" alt="screen shot 2019-02-04 at 8 27 33 pm" src="https://user-images.githubusercontent.com/11078351/52250120-ebb4c980-28bb-11e9-9acf-0ba45096d546.png">
<img width="401" alt="screen shot 2019-02-04 at 8 27 23 pm" src="https://user-images.githubusercontent.com/11078351/52250127-f1aaaa80-28bb-11e9-84bc-7c7713e4bc03.png">

Safari:
<img width="1440" alt="screen shot 2019-02-04 at 8 32 35 pm" src="https://user-images.githubusercontent.com/11078351/52250151-14d55a00-28bc-11e9-99be-518dab5dff42.png">
<img width="505" alt="screen shot 2019-02-04 at 8 32 50 pm" src="https://user-images.githubusercontent.com/11078351/52250161-1bfc6800-28bc-11e9-8fc4-5df2ad48b7fa.png">


I got tired of fighting with the layout, so this is what I got. I will need a more detailed

**Comment by esaruoho** [comment]
thanks, closing :)
