### ISSUE TITLE
Add in section for dev's and link to main project to website

### ISSUE THREAD

**Issue by itsmedavep** [surge-synthesizer/surge-synthesizer.github.io#24]
From the Slack convo on this topic in the #design channel:

From @baconpaul 
<img width="1043" alt="screen shot 2019-01-29 at 8 22 53 am" src="https://user-images.githubusercontent.com/11078351/51917335-f4316f80-23a4-11e9-9f92-e5e06646639d.png"> <-- Image can be used for this. Thanks for the screen!

Secondly I think the main page should hve something for developers. Like another section with a screenshot of developer workflow with some copy like “Developers Welcome” and then “Surge is supported by a community of volunteer open source developers. If you are interested in contributing, we welcome developers who know or want to learn C++, git, and graphic and web design. There’s plenty of open issues and our slack channel can help you find a good first one if you want. Hope over to the <github>, <github issues list> and <developer readme> for more!”

Or some such?

Oh I woudl definitely add something to that copy about “help with testing, replicating bugs, and working with multiple hosts is also welcome. There’s more than enough work!”
And maybe finally something like “a positive upbeat community of volunteer…”
but I’m not a copywriter. I just realized the web page was a good opportunity to share that message!

esaruoho [7:30 AM]
this would definitely be crucial
and if someone is still using 1.52, they can be of enormous help telling us where surgeOpenSource version is at
zvenx for instance has been of enormous help, telling us where things are at with 1.52

baconpaul [7:31 AM]
I’m wondering if we also want to make an open call for peopel to send us tracks which use only surge or almost only surge which are released under (say) cc-4.0-nc-sa or similar (cc-4.0-nc-sa is roughly gpl3-ish but we don’t have to be that uptight)

**Comment by itsmedavep** [comment]
Hey @baconpaul @esaruoho 

Since I am looking at this today, Is the page really more of an open call to everyone to get involved and funnel them to the GitHub project page? 

I ask because this alludes to having a need for the following:
Developers CTA
Testing Needs
Content creation CTA

For example, if this is a broader CTA (call to action) then perhaps the heading is "Contributors Welcome!"

Thoughts?

**Comment by baconpaul** [comment]
Yeah my primary goal is 

1: have a section which mentions developers
2: invite them to GitHub
3: say that this is a developer friendly project 

This is not the spot for developers documentation or issues or anything. Just the invitation / cta and a reminder that this is open source and you can dev it!

**Comment by itsmedavep** [comment]
@baconpaul 

This is done now. It spans a couple of checkins. 

#56  and #57 

Check it out here:

https://surge-synthesizer.github.io/

Thanks for your feedback!
