### ISSUE TITLE
make /manual/ no longer 404

### ISSUE THREAD

**Issue by esaruoho** [surge-synthesizer/surge-synthesizer.github.io#26]
It feels really intuitive to go to https://surge-synthesizer.github.io/manual and expect the manual to load.

feels weird that the actual link is actually https://surge-synthesizer.github.io/surge-manual/

could this be fixed (either a redirect from manual to surge-manual, or the other way around, where the manual is the url for the manual..

**Comment by itsmedavep** [comment]
We can change this. It is based on the front matter at the head of the manual.md file. It’s that permalink bit right at the top. Changing that will change the link. 

Updating the link has implications for the synth. The plug launches the manual with the current link. 

We would need to change it there as well. I don’t think that’s much of an issue. We just need to decide on what the link should be and then make the update.

**Comment by esaruoho** [comment]
@itsmedavep yeah i think /manual/ makes sense. and. a string change for the actual plugin..

and surge-manual could re-direct to /manual/.

i won't do the folder rename cos don't know how.

back to fixing the tables.

**Comment by esaruoho** [comment]
done
