### ISSUE TITLE
Wavetables

### ISSUE THREAD

**Issue by fractalf** [surge-synthesizer/surge-synthesizer.github.io#265]
Hi,
I don't know if this is the right place to post this, but closes I could thing of..

I followed the guide [*Creating-Wavetables-For-Surge*](https://github.com/surge-synthesizer/surge-synthesizer.github.io/wiki/Creating-Wavetables-For-Surge) to create a wavetable from a sample of a saw I have.

My starting point is pretty much a perfect one-cycle saw waveform. When playing it in loop in Audacity, it sound nice deep and crisp.

```sh
> soxi test.wav          

Input File     : 'test.wav'
Channels       : 1
Sample Rate    : 44100
Precision      : 16-bit
Duration       : 00:00:00.05 = 2048 samples = 3.48299 CDDA sectors
File Size      : 4.14k
Bit Rate       : 713k
Sample Encoding: 16-bit Signed Integer PCM
```
![image](https://user-images.githubusercontent.com/5707457/188868407-5f8fd446-4e40-41a5-82bf-1ce68f040448.png)

**The problem** is that when importing this in Surge it sounds "dull", not so crisp, almost like there is a lowpass filter stripping away the high frequencies.

Is this a something that rings a bell? I seem to have done everything by the book, but cannot get the same sound..
(yes, I'm sure there are no filters on in Surge. Used the *Init Saw* patch as a starting point and just switched the waveform)

Converting it
```sh
> mkdir test
> cp test.wav test/
> wt-tool.py -d test -f test.wt -a create -n half   
Creating 'test.wt' with 1 tables of length 2048
Normalizing by half
```

..I also tried without `-n half` and also tried with a wavetable for length 1024 samples, same result.

Thanks for any hints on what the heck is going on here :)

I attached `test.wav` and `test.wt` in a zip file

[test-wavetable-files.zip](https://github.com/surge-synthesizer/surge-synthesizer.github.io/files/9505828/test-wavetable-files.zip)

**UPDATE**

I tried to make the one-cycle waveform from another offset, also touching the "zero line". That actually helped quite a lot! Still not 100% as bright, but that could be fixed with eq I guess.

* Green: Works
* Red: Cuts the high tones

![image](https://user-images.githubusercontent.com/5707457/188879082-a98541a5-aa98-4fc3-a735-cffc8a77c680.png)

**Comment by fractalf** [comment]
Closing this, but if anyone has anything to add, please do :)

**Comment by baconpaul** [comment]
So zero crossings do indeed matter a lot. The assumption is that the frames are roughly periodic

but resolution and frame size does also 

basicalky the wavetable oscillator fills in with (roughly) a band passed sample and hold which emulates 90s era wavetable dacs. This means a lot of that sort of old wavetable sound comes from the interpolation and so 64 vs 256 vs 2048 points matters a lot 

also we have two wavetable consuming oscillators with very different algos. Window with the window set to rectangle may be interesting? 

Don’t know if any of that helps but figured it’s worth adding a comment. And happy to chat here but lots of folks on our discord would also have thoughts im sure if that platform works for you.

**Comment by fractalf** [comment]
Cheers buddy! Any input is most welcome, will dive a bit further into this as well. Maybe even do a wiki pull request of my findings
