### ISSUE TITLE
Update Tuning section(s) for 1.2 release.

### ISSUE THREAD

**Issue by Andreya-Autumn** [surge-synthesizer/surge-synthesizer.github.io#287]
The tuning documentation right now is ok, but could be improved a few ways. This would be nice to adress for the XT1.2 release.

Thoughts that have bounce around are:

- Restructuring to match the tuning menu better? With discrete manual sections to match tuning menu sections.
- Some new screenshots.
- Possibly consolidate everything tuning-related on a single page? (EDIT: nvm, see issue #288 )
- And of course, update the MTS-ESP documentation for the added source feature. :)

**Comment by mthierman** [comment]
"Possibly consolidate everything tuning-related on a single page?"

I think we should make a dedicated page on surge-synth-team site and link back to it, we can put whatever you guys feel is relevant there

**Comment by Andreya-Autumn** [comment]
Agreed! I made two separate issues because most of these points need doing for the 1.2 update anyway. Whereas the larger re-structuring might wait for a later time.

**Comment by Andreya-Autumn** [comment]
For sure! We'll push these changes when the XT1.2 release approaches no matter what. If there's capacity we'll break off to a separate page already at that time, if there ain't we'll defer that to the ShortCircuit XT release. :)

**Comment by Andreya-Autumn** [comment]
Closing as completed via #303
