### ISSUE TITLE
Separate tuning manual

### ISSUE THREAD

**Issue by Andreya-Autumn** [surge-synthesizer/surge-synthesizer.github.io#288]
After a longer conversation, Jacky L and myself are leaning strongly in favor of a separate manual for all tuning-related things. This might seem like overkill right now, but when Shortcircuit releases these features will be shared by both instruments, and it may be really useful to consolidate all of the info in one place. 

With such a solution, it would also be justifiable to include some things that wouldn't fit in the individual product manuals. Such as the text files in the scl library, and the documentation on how to set up microtuned step sequencers in Surge. This would be great, since it would give us one consolidated place to direct newcomers who ask tuning-related questions on our channels.

**Comment by mthierman** [comment]
We should put this on the surge-synth-team site and link it from surge and shortcircuit

**Comment by Andreya-Autumn** [comment]
That's what we were thinking yeah. :)

**Comment by Andreya-Autumn** [comment]
Oh. Closing as completed via #306 et al :)
