### ISSUE TITLE
Left-side nav list item formatting

### ISSUE THREAD

**Issue by j5v** [surge-synthesizer/surge-synthesizer.github.io#347]
Ideally, the left-side nav menu would be a hierarchical list. Instead, it seems to be a flat list with inline formatting attributes for each list item.

1. List formatting indents are unusual (bullets are not indented, and are left of the text margin).
2. HTML is structureed strangely: `<a><li>...</li></a>`  rather than the ideal `<ul><li><a>...</a></li></ul>`

The two might be connected; I haven't explored the build process yet.

![image](https://github.com/surge-synthesizer/surge-synthesizer.github.io/assets/13245475/34371c66-c8be-45e7-8ba2-dc42c44c7c45)

**Comment by mthierman** [comment]
Both issues should be corrected, tested in Chrome & Firefox. We should make the TOC properly hierarchical but it's non-trivial with the current implementation, this should at least fix the layout for now.
