### ISSUE TITLE
Additional content download not working

### ISSUE THREAD

**Issue by boybou** [surge-synthesizer/surge-synthesizer.github.io#359]
When running the download command for the additional content
```
svn checkout https://github.com/surge-synthesizer/surge-synthesizer.github.io/trunk/assets/wiki/Additional%20Content
```

I get the following error
```
svn: E170013: Unable to connect to a repository at URL 'https://github.com/surge-synthesizer/surge-synthesizer.github.io/trunk/assets/wiki/Additional%20Content'
svn: E160013: '/surge-synthesizer/surge-synthesizer.github.io/trunk/assets/wiki/Additional%20Content' path not found
```

**Comment by mthierman** [comment]
It was moved to [surge-extra-content](https://github.com/surge-synthesizer/surge-extra-content/tree/main/Website/wiki/Additional%20Content) repo

**Comment by boybou** [comment]
I see, thank you. Should i leave this issue open? Since the wiki still gives readers the wrong instructions?

**Comment by kendofriendo** [comment]
The updated command still doesn't work, returning those same errors. I recommend using download-directory.github.io or the Refined Github browser extension.
