### ISSUE TITLE
Missing entry for surge-xt v1.3.4 in website Changelog

### ISSUE THREAD

**Issue by luzpaz** [surge-synthesizer/surge-synthesizer.github.io#369]
https://surge-synthesizer.github.io/changelog/  
https://github.com/surge-synthesizer/releases-xt/releases/tag/1.3.4

**Comment by baconpaul** [comment]
ahh yeah 1.3.4 and 1.3.3 were same day release. I updated the changelog to indicate that that log is for 134 thanks
