### ISSUE TITLE
Improve Surge visibility on Facebook + Twitter by fixing social cards

### ISSUE THREAD

**Issue by esaruoho** [surge-synthesizer/surge-synthesizer.github.io#43]
current status:

https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fsurge-synthesizer.github.io
<img width="1440" alt="fullscreen_01_02_2019__8_30" src="https://user-images.githubusercontent.com/4966687/52106498-b7ab8100-25fb-11e9-9a97-d5f4b1c672ee.png">

https://cards-dev.twitter.com/validator
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/4966687/52106511-c134e900-25fb-11e9-9c78-dcf894878183.png">

and sharing on facebook loox like this
<img width="486" alt="facebook" src="https://user-images.githubusercontent.com/4966687/52106521-cc881480-25fb-11e9-9268-12091274c235.png">

i guess this kind of stuff could be tweaked, @itsmedavep ?

**Comment by itsmedavep** [comment]
Unfortunately, I don't have much experience in this area.

Here is some reading for anyone who wants to fix this up:
http://www.cody402.com/2017/09/19/How-to-Make-Awesome-Social-Media-Cards-With-Jekyll.html
https://conductofcode.io/post/social-meta-tags-with-jekyll/

**Comment by esaruoho** [comment]
I can also take a stab at it, now that we have a head.html i can modify. that's where the meta tags go, right?

**Comment by itsmedavep** [comment]
> I can also take a stab at it, now that we have a head.html i can modify. that's where the meta tags go, right?

That would be the one. I think those links walk you through most of it. They are where I would start. Have fun.

**Comment by itsmedavep** [comment]
Related to #64 as well. Fixing these card will help with discoverability and SEO.

**Comment by mthierman** [comment]
I've added the relevant OG meta tags and confirmed everything looks good on Facebook. Closing this up!

![og](https://user-images.githubusercontent.com/68129072/180612170-ddc27201-aae2-404e-8c6a-96b68a9f18dc.png)
