### ISSUE TITLE
Website typos/corrections

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge-synthesizer.github.io#49]
Italics - current state. Normal text - suggested fix.

_If you have used it in the past it will be like welcoming an old friend back into your life. If you are new to Surge, welcome to the party. Come on in the water is fine._
If you have used it in the past, it will be like welcoming an old friend back into your life. If you are new to Surge, welcome to the party. Come on in, the water is fine.

_Quick category-based patch-browser_
I'd remove the dash in patch-browser there.

_Future proof, comes as both a 32 & 64-bit VST plugin (Windows PC coming soon)_
Doesn't this usually have a dash there, future-proof? Also, "a" article is not necessary there. Maybe also remove "Windows PC coming soon" because it's already there, isn't it?

_3 oscillators/voice_
May be nicer to write "3 oscillators per voice" instead

_and Audio-input_
No dash

_/dualsaw_
/dual saw

_The FM2/FM3 oscillators consists of a 1 carrier with 2/3 modulators and various options._
The FM2/FM3 oscillators consists of a carrier and 2 or 3 modulators and various options. 

_Oscillator FM/ringmodulation_
Space between "ring" and "modulation"

_Most oscillator algorithms (except FM2/FM3) are strictly band-limited yet still cover..._
Most oscillator algorithms (except FM2/FM3) are strictly band-limited, yet still cover...

_Filterblock_
I'd add a space there, but then the manual will also need updating. Which it should anyways, eventually. :)

_Two filter-units with arrangeable in 8 different configurations_
Two filter units in 8 different configurations

_Available filter-algorithms: LP12 (3), LP24 (3), LP24L (1-4 poles), HP12 (3), HP24 (3), BP (4), Notch (2), Comb (4), S&H_
Available filter algorithms: LP12 (3 variations), LP24 (3 variations), LP Ladder (1-4 poles), HP12 (3 variations), HP24 (3 variations), BP (4 variations), Notch (2 variations), Comb (4 variations), S&H

_12 LFO-units available to each voice (6 are running on each voice and 6 are shared for the scene)_
12 LFO units available, 6 are per voice and 6 are global for the whole scene

_7 deformable LFO-waveforms + 1 drawable/step-sequencer waveform_
7 deformable LFO waveforms + drawable/step sequencer waveform

_LFO1 allows envelope retriggering when used as stepsequencer_
LFO 1 allows envelope retriggering when used as step sequencer

_2 inserts/scene_
2 inserts per scene

_(EQ, stereo-image control & limiter)_
(EQ, stereo image control and limiter)

System requirements:
Instead of using "an" and "a" articles all the time, I would suggest using bullet points instead.

**Comment by itsmedavep** [comment]
Thanks for this! I'm working on the site today so I will take a pass at these changes while Im in there.

**Comment by itsmedavep** [comment]
All done and picked up on #56 

Thanks for the review of the site! This all is done now. Closing
