### ISSUE TITLE
Releases/Downloads -page

### ISSUE THREAD

**Issue by esaruoho** [surge-synthesizer/surge-synthesizer.github.io#53]
As discussed on #design , 

D/L Page, contains links to nightly builds (preferably with dates!)
The current "release" build

a changes log

and .. maybe .. known issues list

objective of the page is to encourage people to contribute.

**Comment by kzantow** [comment]
@esaruoho probably don't need this anymore, do we?

**Comment by itsmedavep** [comment]
Dont need the contributor part. 

I would like to consider adding a d/l page. That way we could move both the system requirements and all the d/l links to be available there. Have top level links available to download stable put push everything else to a specific d/l page.  I like the change log and known issues as well.
