### ISSUE TITLE
Topbar: "System Requirements" "Downloads" "Contributors"

### ISSUE THREAD

**Issue by esaruoho** [surge-synthesizer/surge-synthesizer.github.io#61]
Suggested on general - add System Requirements, Downloads and Contributors to the top-bar-menu.

They would, in this case, be:

http://surge-synthesizer.github.io/#contributors
http://surge-synthesizer.github.io/#downloads
http://surge-synthesizer.github.io/#systemrequirements

i'm not sure which things from the frontpage could be anchored and added to the topbar.

i guess eventually the Downloads page will be a separate page. but i think there's a ticket about that, too, somewhere.

**Comment by itsmedavep** [comment]
Leaving some notes in case anyone wants to jump in and tackle this one:

https://jekyllrb.com/tutorials/navigation/
https://learn.cloudcannon.com/jekyll/simple-navigation/
http://planetjekyll.github.io/snippets/nav-with-data
