### ISSUE TITLE
Clean up styles and Jekyll"ify" page content

### ISSUE THREAD

**Issue by itsmedavep** [surge-synthesizer/surge-synthesizer.github.io#62]
As well as the page works now, the home.html page is getting to be a bit complex. I would like to break the HTML down a bit and make it easier to work with. 

Jekyll works by injecting HTML fragments into a page. By way of providing an example:

home.html should only include references to these fragments of a page like so:
```
<div class="container mx-auto px-2 py-4">
        {% for post in site.posts %}
          {% include post_block.html %}
        {% endfor %}
      </div>
```

I didnt do that when I made the site. It gets much easier to manage content and you end up dealing with smaller html documents that are easier to understand if you follow the pattern. 

Work to be done

In our context:
Take home.html
Take each section and move them into their own fragment and add to _includes
Update home.html to reference all fragments

Additionally, clean up of the CSS is needed in all kinds of spots. Ive been a bit sloppy with things. I would like to take the time to fix this stuff up before it gets further out of hand. 

The effort will make my life easier. It will make future dev's life easier if they were to work on it.

**Comment by itsmedavep** [comment]
I should also mention that its probably not much effort to do this. Ill just need a bit of uninterrupted time. 

Im thinking I would do this work before taking on creating new pages for the site.

**Comment by itsmedavep** [comment]
When taking on this task, we should also pull in #64 and #43

**Comment by kzantow** [comment]
@itsmedavep you pretty much did this one already, right?

**Comment by itsmedavep** [comment]
I would say I have done half. I still need to remove in line styles (gasp). I can do that now though.

**Comment by itsmedavep** [comment]
https://github.com/surge-synthesizer/surge-synthesizer.github.io/pull/83
https://github.com/surge-synthesizer/surge-synthesizer.github.io/pull/84

closes this out now.
