### ISSUE TITLE
Add Licenses to the documentation

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge-synthesizer.github.io#63]
We should add a "License" section to the documentation which should have the GPL3 text and also this text https://github.com/steinbergmedia/vstgui/blob/develop/LICENSE

The page should read something like

"Licenses"

"Surge Code" The surge code is licensed under <a>GPL3</a>
"VSTGUI" The VSTGUI is licensed under <a>This steinberg license</a>

(gpl3 text here)
(steinberg text here)

Note that steinberg requires this in their license

Thanks

**Comment by itsmedavep** [comment]
> We should add a "License" section to the documentation which should have the GPL3 text and also this text https://github.com/steinbergmedia/vstgui/blob/develop/LICENSE
> 
> The page should read something like
> 
> "Licenses"
> 
> "Surge Code" The surge code is licensed under GPL3
> "VSTGUI" The VSTGUI is licensed under This steinberg license
> 
> (gpl3 text here)
> (steinberg text here)
> 
> Note that steinberg requires this in their license
> 
> Thanks

Hey @baconpaul 

Happy to do this! Just want to clarify where it should go. 

Put this in the manual. Should it go somewhere else?

**Comment by baconpaul** [comment]
Anywhere in “the documentation” meets the spirit and letter of the requirement

Perhaps in the specs section have a license sub section which links to it? And mention the two licenses in the manual with reference to website?

Basically wherever is findable is fine with me!

Thanks so much

**Comment by itsmedavep** [comment]
As they say on TNG 

I will make so! 

This one is kinda a big one (at least in my mind considering the spirit of our project) so Ill try and knock this one off tonight.

Cheers!

**Comment by itsmedavep** [comment]
I hadn’t heard about it previously.  I did watch a metric ton of TNG and DS9 growing up. 


Podcast time these day is Song Exploder Hidden Brain, and Philosophize this.

**Comment by itsmedavep** [comment]
Adding to license is done now on #65

**Comment by baconpaul** [comment]
Cool

And to be sure: We were always in compliance since the installer had gpl3 as did the about screen and we had a link to vst3sdk in the repo. I think of this as more actively compliant! 

Thanks very much

**Comment by itsmedavep** [comment]
Ah! Of course. 

When I wrote that last night I was thinking that there was an additional requirement to be specifically in the docs. 

But you know, I read both of those as I was adding them to the manual. Didn’t even register. 

For future reference, I was incorrect in implying we were not in compliance.

As @baconpaul stated we have always been in compliance. It was a poor choice of words on my part. 

Mea cupla!

**Comment by itsmedavep** [comment]
Im closing this one. As of now the manual contains a license section.

**Comment by baconpaul** [comment]
Thanks Dave!
