### ISSUE TITLE
increase findability of surge-synthesizer.github.io

### ISSUE THREAD

**Issue by esaruoho** [surge-synthesizer/surge-synthesizer.github.io#64]
I just got told by a Finnish friend of mine that he had tried to find Surge by googling for `vember audio surge 64bit mac` and only found http://github.com/kurasu/surge/releases

i wonder if there's something we can do to fix this, when it comes to keywords/meta tags or something? i don't know much about this stuff.

**Comment by itsmedavep** [comment]
We can look into SEO stuff. There is probably a bunch we can do to help. 

I’m no expert with SEO. Like 0 experience. I do have a high level understanding though. 

One of the main things is to have other site link to us. So embedding links in the releases and main project pages that point to the website is a easy way to help. 

There’s a bunch to SEO. Not the least of which is that Google doesn’t tell ANYONE how their search works. 

This can be a bunch of effort. I’m not suggesting we shouldn’t try and do something about. Quite to the contrary actually. 

I’ll mull it over and formulate a plan in this thread. 

Keep em coming!

**Comment by itsmedavep** [comment]
Also this is related to #43

**Comment by mkruselj** [comment]
This basically fixed itself due to how popular Surge became in the past couple years. Closing!

**Comment by mthierman** [comment]
This was not actually closed, we have proper OG tags and surge is pretty discoverable. Closing it up.
