### ISSUE TITLE
Testimonials and sourcing of testimonials

### ISSUE THREAD

**Issue by esaruoho** [surge-synthesizer/surge-synthesizer.github.io#68]
Suggestion:

We could definitely have testimonials for Surge on a page somewhere. Posted about it on #design and @itsmedavep seemed to agree.

I'll start by asking if Inigo Kennedy would be interested in providing a testimonial - and send him the one he wrote on KVR.

@itsmedavep is correct that there should be 3-5 of them. Will be posting them when I get permission from the wordy culprits!!

**Comment by esaruoho** [comment]
Got permission from Inigo Kennedy:

```
For me Surge is an absolute desert island synth and it is capable of beautiful and captivating sounds.
It's one of the very few plugins I've come across that hits the difficult to find but very sweet spot between being intuitive and clear to work with but at the same time the sound can feel very organic and inspirational.
The modulation system is a stroke of genius and adding movement to sounds is so easy and flexible. There is this complexity and depth available but it feels neither complex nor deep. That's quite magic! To put it another way, I find that it feels like I'm always working with it and not struggling against it (as can be the case with so many other synths - software or hardware).
```

**Comment by esaruoho** [comment]
![364c2b66-5260-4c5a-bc61-2d37613f5612](https://user-images.githubusercontent.com/4966687/52518720-d2af6e00-2c57-11e9-84bf-2f961d68fd75.jpeg)
Proof of testimonial agreement

**Comment by mthierman** [comment]
So we have reviews on this page but they look to be mostly old versions of Surge: https://surge-synth-team.org/reviews-and-guides/

The surge page itself has Roger Linn and the One Synth Challenge which I think is pretty good.

Perhaps we could collect some XT content and update the surge-synth-team page and link back to it, or create a new page on the surge site itself?
