### ISSUE TITLE
Dates of build next to versions on website

### ISSUE THREAD

**Issue by esaruoho** [surge-synthesizer/surge-synthesizer.github.io#71]
from KVR:

```
Can someone put the release dates up on the builds
site by the downloads links please so people can
tell if there is a new one.
```

**Comment by baconpaul** [comment]
I think this needs @kzantow to do one but of automation

Maybe the easiest thing is in each release add a file called “release-date-yyyymmddhhmmss.txt” which people can just see

**Comment by itsmedavep** [comment]
There is a date. 

The releases say when it was built. Checking just now the releases page say the latest ones were built 21 hrs ago. 

I’m not opposed to any of this. Just pointing out that the releases site already has some info. 

So what is it that specifically that is needed?

I can’t see how to upload a screenshot on my phone but:

https://github.com/surge-synthesizer/releases/releases

That page is explicit about when it was built.

**Comment by baconpaul** [comment]
Oh yeah!

How does include work I. Jekyll work Dave? If kzantow updated a little file saying “last built on” in the website repo could you slurp it in?

**Comment by esaruoho** [comment]
@itsmedavep yeah, the dates are there.. but not on http://surge-synthesizer.github.io/#downloads :)

**Comment by itsmedavep** [comment]
> Oh yeah!
> 
> How does include work I. Jekyll work Dave? If kzantow updated a little file saying “last built on” in the website repo could you slurp it in?

Presumably, yes but thats just me guessing! Most of this stuff is manageable just would take a bit of research. They are just normal sites at the end of "Jekyll"ing so Im inclined to believe that we can come up with something.

**Comment by itsmedavep** [comment]
> @itsmedavep yeah, the dates are there.. but not on http://surge-synthesizer.github.io/#downloads :)

Ah. I see. Well, if you would like the download section on the Github IO page to have dates that will take some figuring out. Not impossible or anything I would just need to work through how to do it. 

When I can get the cycles Ill make this one a priority.  Ill try and figure out a "built on" scheme. If anyone has suggestions as to how you would normally do this with a site Im all EARS. Presumably some javascript will take care of it. 

Still kinda jammed up with client stuff this weekend. I may get some Surge cycles tonight. Ill do some research and report back.

**Comment by esaruoho** [comment]
done, closing
