### ISSUE TITLE
VST2 64 bit .dll not recognised by FL Studio

### ISSUE THREAD

**Issue by Flayzen** [surge-synthesizer/surge-synthesizer.github.io#88]
The VST2 64 bit version of Surge is not being detected by FL Studio 20.1.1 in Windows 10 when scanning for new plugins. Yes, I have configured the search to look in the correct folder. The VST3 version is detected.

**Comment by Flayzen** [comment]
Closing this as I found another issues page for Surge. Not sure why there are two pages but the other one seems busier than this one.

**Comment by baconpaul** [comment]
This one is for the surge website; the other one is for the surge synth. (Your issue belongs with the synth so thanks for closing and moving it).
